
export const INITIAL_STONES_PER_PIT = 4;
export const PLAYER_ONE_PITS = [0, 1, 2, 3, 4, 5];
export const PLAYER_TWO_PITS = [7, 8, 9, 10, 11, 12];
export const PLAYER_ONE_STORE = 6;
export const PLAYER_TWO_STORE = 13;

export const INITIAL_BOARD = [
  INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT,
  0, // Player 1 Store
  INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT, INITIAL_STONES_PER_PIT,
  0, // Player 2 Store
];
